systemLog:
   destination: file
   path: "/var/log/mongodb/mongod.log"
   logAppend: true

storage:
   dbPath: "/data/db"
   journal:
      enabled: true

processManagement:
   fork: false

net:
   bindIp: 0.0.0.0
   port: 27016

setParameter:
   enableLocalhostAuthBypass: false

replication:
   oplogSizeMB: 1024
   replSetName: "test161"

security:
   keyFile: /data/mongodb-keyfile
   authorization: enabled
